location: "sandbox"
image:
  repository: "localhost:5001/bioscfg"
  tag: latest
  pullPolicy: Always
env:
  FLEETDB_ENDPOINT: http://fleetdb:8000
  FLEETDB_DISABLE_OAUTH: true
  NATS_URL: "nats://nats:4222"
  NATS_CONNECT_TIMEOUT: 60s
  NATS_KV_REPLICAS: 1
  # telemetry configuration
  OTEL_EXPORTER_OTLP_ENDPOINT: jaeger:4317
  OTEL_EXPORTER_OTLP_INSECURE: true