apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-service: bioscfg
  name: bioscfg
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-service: bioscfg
  template:
    metadata:
      labels:
        k8s-service: bioscfg
    spec:
      terminationGracePeriodSeconds: 1200
      containers:
        - name: bioscfg
          image: {{ .Values.image.repository.url }}/bioscfg:{{ .Values.image.repository.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [
           "bioscfg",
           "run",
           "--config",
           "/etc/bioscfg/config.yaml",
           "--enable-pprof",
           "--log-level",
           "debug",
          ]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/bioscfg
            - name: nats-creds-volume
              mountPath: /etc/nats
              readOnly: true
          env:
          {{- if .Values.env.endpoints.fleetdb.authenticate }}
            - name: ENDPOINTS_FLEETDB_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bioscfg-secrets
                  key: fleetdb-oidc-client-secret
          {{- end }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.env.endpoints.otel.url }}"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "{{ not .Values.env.endpoints.otel.authenticate }}"
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          resources:
            limits:
              cpu: 200m
              memory: 500M
            requests:
              cpu: 200m
              memory: 500M
          ports:
            - name: metrics-port
              containerPort: 9090
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics-port
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics-port
            initialDelaySeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: bioscfg-config
        - name: nats-creds-volume
          secret:
            secretName: bioscfg-secrets
            items:
              - key: bioscfg-nats-creds
                path: nats.creds
      restartPolicy: Always
